### ISSUE TITLE
Lootbox

### ISSUE THREAD

**Issue by djnume** [Aioxas/ax-cogs#5]
`Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/discord/ext/commands/core.py", line 50, in wrapped
    ret = yield from coro(*args, **kwargs)
  File "/root/Red-DiscordBot/cogs/lootbox.py", line 143, in info
    await self.bot.say("You can get the following items from the box:\n{}".format("\n".join(box)))
  File "/usr/local/lib/python3.5/dist-packages/discord/ext/commands/bot.py", line 309, in _augmented_msg
    msg = yield from coro
  File "red.py", line 97, in send_message
    return await super().send_message(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/discord/client.py", line 1152, in send_message
    data = yield from self.http.send_message(channel_id, content, guild_id=guild_id, tts=tts, embed=embed)
  File "/usr/local/lib/python3.5/dist-packages/discord/http.py", line 199, in request
    raise HTTPException(r, data)
discord.errors.HTTPException: BAD REQUEST (status code: 400)`

Unable to show information about the Lootbox, due to the message being too long.

Unable to use `>box sim "winter"` without following it with a set item that is always present in the box. Scenario for where no such item exist has not been included.

Unable to add multiple items when creating a new box, due to the Discord Message Length Limit. Having to edit `servers.json` to add multiple such items.

**Comment by Aioxas** [comment]
Try the newest commit to see if it works, it will not be an embed, there are two new commands in the box edit group.
